## NumPy Exercises

Importing NumPy and printing version number

In [95]:
import numpy as np
print((np.__version__))

1.21.5


### Set the Numpy random seed to 12345 in order to reproduce your results

In [96]:
np.random.seed(12345)

### EXERCISE 1 - Element-wise addition of 2 numpy arrays
Create 2 two-dimensional numpy arrays x1 and x2

x1 is a random integers array in the range of 10 and size 10
x2 is a random floats between (0,1] and size 10

Add x1 to x2 element wise and print the results

In [97]:
x1 = np.random.randint(10, size=10)
x2 = np.random.random((10))
result = x1 + x2
result

array([2.6531771 , 5.74890664, 1.65356987, 4.74771481, 9.96130674,
       5.0083883 , 2.10644438, 1.29870371, 6.65641118, 1.80981255])

### EXERCISE 2 - Multiplying a matrix (numpy array) by a scalar
Create a numpy array (matrix), then get a numpy array output which is equal to the original matrix multiplied by a scalar

create a matrix of random integers in the range of 10 with dimensions (5,5) and call it x3

Add 5 to x3

In [98]:
simple_array = np.array([1,2,3,4,5])
array_multiplied_scalar = 5 * simple_array
array_multiplied_scalar

array([ 5, 10, 15, 20, 25])

In [99]:
x3 = np.random.randint(10, size=(5,5))
x3

array([[8, 7, 1, 7, 4],
       [0, 3, 5, 7, 3],
       [1, 5, 2, 5, 3],
       [8, 5, 2, 5, 3],
       [0, 6, 8, 0, 5]])

In [100]:
added_x3 = 5 + x3
added_x3

array([[13, 12,  6, 12,  9],
       [ 5,  8, 10, 12,  8],
       [ 6, 10,  7, 10,  8],
       [13, 10,  7, 10,  8],
       [ 5, 11, 13,  5, 10]])

### EXERCISE 3 - Identity Matrix
Create an identity matrix of dimension 4-by-4

In [101]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### EXERCISE 4 - Array re-dimensioning
Reshape x1[:-1] into a (3,3) array

In [102]:
x1

array([2, 5, 1, 4, 9, 5, 2, 1, 6, 1])

In [103]:
x1[:-1].reshape(3,3)

array([[2, 5, 1],
       [4, 9, 5],
       [2, 1, 6]])

In [104]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3)) # (1 row, and 3 columns)

array([[1, 2, 3]])

In [105]:
# row vector via newaxis
x[np.newaxis, :] # [np.newaxis = Arrange elements into row, : = all elements]

array([[1, 2, 3]])

In [106]:
# column vector via newaxis
x[:, np.newaxis] # [: = all elements, np.newaxis = Arrange elements into column]

array([[1],
       [2],
       [3]])

### EXERCISE 5 - Horizontal Stacking of Numpy Arrays // Spliting of Arrays
Stack x1 and x2 horizontally

In [123]:
x1

array([2, 5, 1, 4, 9, 5, 2, 1, 6, 1])

In [124]:
x2

array([0.6531771 , 0.74890664, 0.65356987, 0.74771481, 0.96130674,
       0.0083883 , 0.10644438, 0.29870371, 0.65641118, 0.80981255])

In [132]:
x44 = np.random.randint(10, size =10)
x44

array([9, 5, 0, 8, 8, 2, 0, 2, 0, 6])

In [133]:
np.hstack([x1, x44])

array([2, 5, 1, 4, 9, 5, 2, 1, 6, 1, 9, 5, 0, 8, 8, 2, 0, 2, 0, 6])

In [110]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x11, x12, x13 = np.split(x, [3, 5]) #will only accept n-1 indices parameters (x1, x2, x3 = 3, [3, 5] = n-1 = 2) // [Split at third index, then again at 5th index]
print(x11, x12, x13)

[1 2 3] [99 99] [3 2 1]


In [111]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x11,x12 = np.split(x, [4]) #Will split starting at count = 1, in this example it will split at the fourth number
print(x11,x12)

[ 1  2  3 99] [99  3  2  1]


Horizontal SPLIT

In [112]:
grid = np.arange(16).reshape((4, 4)) #creates a range from (0 - (n-1) = 16 - 1 = 15), then reshapes that range into a (4 row, 4 column) grid
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [113]:
left, right = np.hsplit(grid, [2])
print(left) #prints left two elements (index 1 and 2) of grid
print(right) #prints right two elements (index 3 and 4) of grid 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### EXERCISE 6 - Vertically Stacking of Numpy Arrays
Stack x1 and x2 vertically

In [114]:
np.vstack([x1, x2])

array([[2.00000000e+00, 5.00000000e+00, 1.00000000e+00, 4.00000000e+00,
        9.00000000e+00, 5.00000000e+00, 2.00000000e+00, 1.00000000e+00,
        6.00000000e+00, 1.00000000e+00],
       [6.53177097e-01, 7.48906638e-01, 6.53569871e-01, 7.47714809e-01,
        9.61306736e-01, 8.38829794e-03, 1.06444377e-01, 2.98703714e-01,
        6.56411183e-01, 8.09812553e-01]])

In [115]:
upper, lower = np.vsplit(grid, [2]) #Starting at 1-based index
print(upper) #prints first two rows of grid
print(lower) #prints last two rows of grid

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


### EXERCISE 7 - Custom Sequence Generation
Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....

You need to use the short form of the for loop to create a list and then convert this list into a Numpy array

In [116]:
np.array([np.arange(0,102,2) for i in np.arange(0,1)])

array([[  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
         26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
         52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
         78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100]])

In [117]:
np.array([range(i, i + 3) for i in [2, 4, 6]]) # Sets three ranges, from [2, 4, 6] to [2 + 3, 4 + 3, 6 + 3] and displays the values starting from i to i + 3

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### EXERCISE 8 - Generation of given count of equally spaced numbers within a specified range
Output a sequence of equally gapped 5 numbers in the range 0 to 100 (both inclusive) <br>
hint: use `linspace`

In [118]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

### EXERCISE 9 - Array Generation of random integers within a specified range

Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive). Call this array x4

[start:stop:step]

In [119]:
x4 = np.random.randint(10 , size=(5,5))
x4

array([[6, 8, 9, 2, 2],
       [2, 9, 7, 5, 7],
       [1, 0, 9, 3, 0],
       [3, 0, 6, 2, 1],
       [5, 8, 6, 5, 1]])

In [120]:
x3[::-1, ::-1] # (Reverse rows, reverse columns)

array([[5, 0, 8, 6, 0],
       [3, 5, 2, 5, 8],
       [3, 5, 2, 5, 1],
       [3, 7, 5, 3, 0],
       [4, 7, 1, 7, 8]])

In [134]:
print(x2[0, :])  # print everything in first ROW of x2

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
print(x2[:, 0])  # print everything in COLUMN 0 of x2

In [ ]:
x2_sub[0, 0] = 99 #change element in [first row, first column]
print(x2_sub)

### EXERCISE 10 - Matrix Multiplication

Multiply x3 with x4

In [ ]:
x3

array([[8, 7, 1, 7, 4],
       [0, 3, 5, 7, 3],
       [1, 5, 2, 5, 3],
       [8, 5, 2, 5, 3],
       [0, 6, 8, 0, 5]])

In [ ]:
x4

array([[6, 8, 9, 2, 2],
       [2, 9, 7, 5, 7],
       [1, 0, 9, 3, 0],
       [3, 0, 6, 2, 1],
       [5, 8, 6, 5, 1]])

In [ ]:
x3 * x4

array([[48, 56,  9, 14,  8],
       [ 0, 27, 35, 35, 21],
       [ 1,  0, 18, 15,  0],
       [24,  0, 12, 10,  3],
       [ 0, 48, 48,  0,  5]])

MAX, MIN AND OTHER AGGREGATE FUNCTIONS

In [ ]:
M = np.random.random((3, 4))
print(M)
#sum(M) #Sums the rows accross
M.sum() #Sums aggregate of the array


[[0.92649017 0.51587977 0.07215988 0.5675083 ]
 [0.61524318 0.94154629 0.41536335 0.26443997]
 [0.09739317 0.48584422 0.46466286 0.02975932]]


5.396290497947823

In [ ]:
M.min(axis=0) #Axis =0 will give min in the columns

array([0.09739317, 0.48584422, 0.07215988, 0.02975932])

In [ ]:
M.min(axis=1) #Axis =1 will give min in the rows

array([0.07215988, 0.26443997, 0.02975932])